---
- apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
  - byobu
  - git-core
  - htop
  - tmux
- git:
    repo: "https://github.com/colstrom/dotfiles.git"
    dest: /home/colstrom/.dotfiles
    force: yes
- sudo_user: colstrom
  shell: ./setup.sh
  args:
    chdir: /home/colstrom/.dotfiles
    creates: /home/colstrom/.config/fish/config.fish
- file:
    path: /home/colstrom
    owner: colstrom
    group: colstrom
    recurse: yes
